toggles:
  isLocal:

replicaCount: 1

image:
  repository:
  tag:

service:
  type: ClusterIP
  port: 3002
  externalPort: 3002
  domainName:
  tls:

resources:
  limits:
    cpu: 500m
    memory: 4G
  requests:
    cpu: 500m
    memory: 4G
